# Generated by Django 3.2.3 on 2021-06-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_auto_20210627_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='number',
            field=models.CharField(max_length=15),
        ),
    ]
