# Generated by Django 3.2.3 on 2021-06-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_auto_20210629_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='element',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='revision',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
